CREATE DATABASE IF NOT EXISTS ecommerceDB;

USE ecommerceDB;

CREATE TABLE IF NOT EXISTS Users (
    UserID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Address VARCHAR(255),
    Password VARCHAR(255),
    PaymentInfo VARCHAR(255),
    Balance DECIMAL(19,4),
    PRIMARY KEY(UserID)
);

CREATE TABLE IF NOT EXISTS Items (
    ItemID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(25) NOT NULL,
    Type VARCHAR(25) NOT NULL,
    Size VARCHAR(10) NOT NULL,
    Description VARCHAR(255) NOT NULL DEFAULT 'None.',
    Quantity INT NOT NULL DEFAULT 5,
    Price DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS Invoices (
    InvoicesID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL FOREIGN KEY (UserID) REFERENCES Users(UserID), 
    ClientName VARCHAR(255),
    InvoiceDate DATE,
    TotalAmount DECIMAL(19,4),
    PRIMARY KEY(InvoicesID)
);
CREATE TABLE IF NOT EXISTS InvoiceItems (
    ItemID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    InvoiceID INT NOT NULL FOREIGN KEY (InvoiceID) REFERENCES Invoices(InvoiceID),
    ItemDescription VARCHAR(255),
    Quantity INT,
    LineTotal DECIMAL(19,4),
    PRIMARY KEY(ItemID)
);

CREATE TABLE IF NOT EXISTS Payments (
    PaymentID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    InvoiceID INT NOT NULL FOREIGN KEY (InvoiceID) REFERENCES Invoices(InvoiceID),
    PaymentDate DATE,
    Amount DECIMAL(19,4),
    PaymentMethod VARCHAR(255),
    PRIMARY KEY(PaymentID)
);